/**
 * Generated by Style Dictionary 5.3.3
 * Tailwind v4 preset — maps design tokens to utility classes.
 * Do not edit directly — regenerate with: npm run tokens:build
 */
export default {
  theme: {
    extend: {
      colors: {
    'color-brand-primary': 'var(--vp-color-brand-primary)',
    'color-brand-primary-light': 'var(--vp-color-brand-primary-light)',
    'color-brand-primary-dark': 'var(--vp-color-brand-primary-dark)',
    'color-brand-accent': 'var(--vp-color-brand-accent)',
    'color-brand-accent-light': 'var(--vp-color-brand-accent-light)',
    'color-brand-accent-dark': 'var(--vp-color-brand-accent-dark)',
    'color-feedback-success': 'var(--vp-color-feedback-success)',
    'color-feedback-warning': 'var(--vp-color-feedback-warning)',
    'color-feedback-danger': 'var(--vp-color-feedback-danger)',
    'color-feedback-info': 'var(--vp-color-feedback-info)',
    'color-neutral-base': 'var(--vp-color-neutral-base)',
    'color-neutral-muted': 'var(--vp-color-neutral-muted)',
    'color-neutral-dark': 'var(--vp-color-neutral-dark)',
    'color-neutral-light': 'var(--vp-color-neutral-light)',
    'color-surface-primary': 'var(--vp-color-surface-primary)',
    'color-surface-secondary': 'var(--vp-color-surface-secondary)',
    'color-surface-tertiary': 'var(--vp-color-surface-tertiary)',
    'color-border-base': 'var(--vp-color-border-base)',
    'color-border-light': 'var(--vp-color-border-light)',
    'color-border-dark': 'var(--vp-color-border-dark)'
      },
      spacing: {
    'xs': 'var(--vp-spacing-xs)',
    'sm': 'var(--vp-spacing-sm)',
    'md': 'var(--vp-spacing-md)',
    'lg': 'var(--vp-spacing-lg)',
    'xl': 'var(--vp-spacing-xl)',
    '2xl': 'var(--vp-spacing-2xl)',
    '3xl': 'var(--vp-spacing-3xl)',
    '4xl': 'var(--vp-spacing-4xl)'
      },
      fontSize: {
    'xs': 'var(--vp-font-size-xs)',
    'sm': 'var(--vp-font-size-sm)',
    'base': 'var(--vp-font-size-base)',
    'lg': 'var(--vp-font-size-lg)',
    'xl': 'var(--vp-font-size-xl)',
    '2xl': 'var(--vp-font-size-2xl)',
    '3xl': 'var(--vp-font-size-3xl)'
      },
      fontWeight: {
    'normal': 'var(--vp-font-weight-normal)',
    'medium': 'var(--vp-font-weight-medium)',
    'semibold': 'var(--vp-font-weight-semibold)',
    'bold': 'var(--vp-font-weight-bold)'
      },
    },
  },
};
