/**
 * Generated by Style Dictionary 5.3.3
 * Do not edit directly — regenerate with: npm run tokens:build
 */

export type VpTokenName =
  | '--vp-color-brand-primary'
  | '--vp-color-brand-primary-light'
  | '--vp-color-brand-primary-dark'
  | '--vp-color-brand-accent'
  | '--vp-color-brand-accent-light'
  | '--vp-color-brand-accent-dark'
  | '--vp-color-feedback-success'
  | '--vp-color-feedback-warning'
  | '--vp-color-feedback-danger'
  | '--vp-color-feedback-info'
  | '--vp-color-neutral-base'
  | '--vp-color-neutral-muted'
  | '--vp-color-neutral-dark'
  | '--vp-color-neutral-light'
  | '--vp-color-surface-primary'
  | '--vp-color-surface-secondary'
  | '--vp-color-surface-tertiary'
  | '--vp-color-border-base'
  | '--vp-color-border-light'
  | '--vp-color-border-dark'
  | '--vp-gradient-brand-primary'
  | '--vp-gradient-brand-accent'
  | '--vp-gradient-surface-dark'
  | '--vp-gradient-surface-glow'
  | '--vp-gradient-success'
  | '--vp-gradient-danger'
  | '--vp-motion-duration-instant'
  | '--vp-motion-duration-fast'
  | '--vp-motion-duration-normal'
  | '--vp-motion-duration-slow'
  | '--vp-motion-duration-deliberate'
  | '--vp-motion-easing-default'
  | '--vp-motion-easing-in'
  | '--vp-motion-easing-out'
  | '--vp-motion-easing-spring'
  | '--vp-spacing-xs'
  | '--vp-spacing-sm'
  | '--vp-spacing-md'
  | '--vp-spacing-lg'
  | '--vp-spacing-xl'
  | '--vp-spacing-2xl'
  | '--vp-spacing-3xl'
  | '--vp-spacing-4xl'
  | '--vp-font-family-sans'
  | '--vp-font-family-mono'
  | '--vp-font-size-xs'
  | '--vp-font-size-sm'
  | '--vp-font-size-base'
  | '--vp-font-size-lg'
  | '--vp-font-size-xl'
  | '--vp-font-size-2xl'
  | '--vp-font-size-3xl'
  | '--vp-font-weight-normal'
  | '--vp-font-weight-medium'
  | '--vp-font-weight-semibold'
  | '--vp-font-weight-bold'
  | '--vp-font-lineHeight-tight'
  | '--vp-font-lineHeight-normal'
  | '--vp-font-lineHeight-relaxed'
  | '--vp-font-lineHeight-loose'
  | '--vp-font-letterSpacing-tight'
  | '--vp-font-letterSpacing-normal'
  | '--vp-font-letterSpacing-wide';

export interface VpTokenDefinition {
  value: string;
  description: string;
  styleId: string;
}

export const VP_TOKENS: Record<VpTokenName, VpTokenDefinition> = {
  '--vp-color-brand-primary': { value: '#7c3aed', description: 'Primary brand purple', styleId: 'color-brand-primary' },
  '--vp-color-brand-primary-light': { value: '#a78bfa', description: 'Lighter primary for hover states', styleId: 'color-brand-primary-light' },
  '--vp-color-brand-primary-dark': { value: '#5b21b6', description: 'Darker primary for active states', styleId: 'color-brand-primary-dark' },
  '--vp-color-brand-accent': { value: '#ec4899', description: 'Accent pink for highlights', styleId: 'color-brand-accent' },
  '--vp-color-brand-accent-light': { value: '#f472b6', description: 'Lighter accent for hover', styleId: 'color-brand-accent-light' },
  '--vp-color-brand-accent-dark': { value: '#be185d', description: 'Darker accent for active', styleId: 'color-brand-accent-dark' },
  '--vp-color-feedback-success': { value: '#10b981', description: 'Success/completion green', styleId: 'color-feedback-success' },
  '--vp-color-feedback-warning': { value: '#f59e0b', description: 'Warning amber', styleId: 'color-feedback-warning' },
  '--vp-color-feedback-danger': { value: '#ef4444', description: 'Error/danger red', styleId: 'color-feedback-danger' },
  '--vp-color-feedback-info': { value: '#06b6d4', description: 'Info cyan', styleId: 'color-feedback-info' },
  '--vp-color-neutral-base': { value: '#334155', description: 'Neutral slate-700', styleId: 'color-neutral-base' },
  '--vp-color-neutral-muted': { value: '#64748b', description: 'Muted slate-500', styleId: 'color-neutral-muted' },
  '--vp-color-neutral-dark': { value: '#0f172a', description: 'Dark slate-900 — background', styleId: 'color-neutral-dark' },
  '--vp-color-neutral-light': { value: '#f1f5f9', description: 'Light slate-100 — text on dark', styleId: 'color-neutral-light' },
  '--vp-color-surface-primary': { value: '#1e293b', description: 'Primary surface color', styleId: 'color-surface-primary' },
  '--vp-color-surface-secondary': { value: '#334155', description: 'Secondary surface', styleId: 'color-surface-secondary' },
  '--vp-color-surface-tertiary': { value: '#475569', description: 'Tertiary surface', styleId: 'color-surface-tertiary' },
  '--vp-color-border-base': { value: '#475569', description: 'Standard border color', styleId: 'color-border-base' },
  '--vp-color-border-light': { value: '#64748b', description: 'Light border', styleId: 'color-border-light' },
  '--vp-color-border-dark': { value: '#334155', description: 'Dark border', styleId: 'color-border-dark' },
  '--vp-gradient-brand-primary': { value: 'linear-gradient(135deg, #7c3aed, #ec4899)', description: 'Primary brand gradient — purple to pink', styleId: 'gradient-brand-primary' },
  '--vp-gradient-brand-accent': { value: 'linear-gradient(135deg, #ec4899, #f59e0b)', description: 'Accent gradient — pink to amber', styleId: 'gradient-brand-accent' },
  '--vp-gradient-surface-dark': { value: 'linear-gradient(180deg, #0f172a, #1e293b)', description: 'Dark surface gradient', styleId: 'gradient-surface-dark' },
  '--vp-gradient-surface-glow': { value: 'linear-gradient(180deg, #1e293b, #334155, #1e293b)', description: 'Surface glow — subtle center highlight', styleId: 'gradient-surface-glow' },
  '--vp-gradient-success': { value: 'linear-gradient(135deg, #10b981, #06b6d4)', description: 'Success/positive gradient — green to cyan', styleId: 'gradient-success' },
  '--vp-gradient-danger': { value: 'linear-gradient(135deg, #ef4444, #ec4899)', description: 'Danger/error gradient — red to pink', styleId: 'gradient-danger' },
  '--vp-motion-duration-instant': { value: '50ms', description: 'Instant feedback — micro-interactions', styleId: 'motion-duration-instant' },
  '--vp-motion-duration-fast': { value: '150ms', description: 'Fast transitions — hover, focus', styleId: 'motion-duration-fast' },
  '--vp-motion-duration-normal': { value: '250ms', description: 'Normal transitions — expand, collapse', styleId: 'motion-duration-normal' },
  '--vp-motion-duration-slow': { value: '400ms', description: 'Slow transitions — page-level animations', styleId: 'motion-duration-slow' },
  '--vp-motion-duration-deliberate': { value: '700ms', description: 'Deliberate entrance/exit animations', styleId: 'motion-duration-deliberate' },
  '--vp-motion-easing-default': { value: '0.4, 0, 0.2, 1', description: 'Default easing — ease-in-out', styleId: 'motion-easing-default' },
  '--vp-motion-easing-in': { value: '0.4, 0, 1, 1', description: 'Ease-in for exits', styleId: 'motion-easing-in' },
  '--vp-motion-easing-out': { value: '0, 0, 0.2, 1', description: 'Ease-out for entrances', styleId: 'motion-easing-out' },
  '--vp-motion-easing-spring': { value: '0.175, 0.885, 0.32, 1.275', description: 'Spring overshoot — playful interactions', styleId: 'motion-easing-spring' },
  '--vp-spacing-xs': { value: '0.25rem', description: '4px — extra small spacing', styleId: 'spacing-xs' },
  '--vp-spacing-sm': { value: '0.5rem', description: '8px — small spacing', styleId: 'spacing-sm' },
  '--vp-spacing-md': { value: '1rem', description: '16px — medium/base spacing', styleId: 'spacing-md' },
  '--vp-spacing-lg': { value: '1.5rem', description: '24px — large spacing', styleId: 'spacing-lg' },
  '--vp-spacing-xl': { value: '2rem', description: '32px — extra large spacing', styleId: 'spacing-xl' },
  '--vp-spacing-2xl': { value: '3rem', description: '48px — 2x extra large', styleId: 'spacing-2xl' },
  '--vp-spacing-3xl': { value: '4rem', description: '64px — 3x extra large', styleId: 'spacing-3xl' },
  '--vp-spacing-4xl': { value: '6rem', description: '96px — 4x extra large', styleId: 'spacing-4xl' },
  '--vp-font-family-sans': { value: 'Inter, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif', description: 'Primary sans-serif font stack', styleId: 'font-family-sans' },
  '--vp-font-family-mono': { value: 'Fira Code, Cascadia Code, JetBrains Mono, ui-monospace, monospace', description: 'Monospace font stack for terminal/code', styleId: 'font-family-mono' },
  '--vp-font-size-xs': { value: '0.75rem', description: '12px — extra small text', styleId: 'font-size-xs' },
  '--vp-font-size-sm': { value: '0.875rem', description: '14px — small text', styleId: 'font-size-sm' },
  '--vp-font-size-base': { value: '1rem', description: '16px — base text', styleId: 'font-size-base' },
  '--vp-font-size-lg': { value: '1.125rem', description: '18px — large text', styleId: 'font-size-lg' },
  '--vp-font-size-xl': { value: '1.25rem', description: '20px — extra large text', styleId: 'font-size-xl' },
  '--vp-font-size-2xl': { value: '1.5rem', description: '24px — heading large', styleId: 'font-size-2xl' },
  '--vp-font-size-3xl': { value: '1.875rem', description: '30px — heading xlarge', styleId: 'font-size-3xl' },
  '--vp-font-weight-normal': { value: '400', description: 'Normal weight', styleId: 'font-weight-normal' },
  '--vp-font-weight-medium': { value: '500', description: 'Medium weight', styleId: 'font-weight-medium' },
  '--vp-font-weight-semibold': { value: '600', description: 'Semibold weight', styleId: 'font-weight-semibold' },
  '--vp-font-weight-bold': { value: '700', description: 'Bold weight', styleId: 'font-weight-bold' },
  '--vp-font-lineHeight-tight': { value: '1.2', description: 'Tight line height — headings', styleId: 'line-height-tight' },
  '--vp-font-lineHeight-normal': { value: '1.5', description: 'Normal line height — body', styleId: 'line-height-normal' },
  '--vp-font-lineHeight-relaxed': { value: '1.75', description: 'Relaxed line height — readable blocks', styleId: 'line-height-relaxed' },
  '--vp-font-lineHeight-loose': { value: '2', description: 'Loose line height — spacious layout', styleId: 'line-height-loose' },
  '--vp-font-letterSpacing-tight': { value: '-0.02em', description: 'Tight tracking for large headings', styleId: 'letter-spacing-tight' },
  '--vp-font-letterSpacing-normal': { value: '0em', description: 'Normal tracking', styleId: 'letter-spacing-normal' },
  '--vp-font-letterSpacing-wide': { value: '0.025em', description: 'Wide tracking for small caps', styleId: 'letter-spacing-wide' }
};

export function getToken(name: VpTokenName): VpTokenDefinition {
  return VP_TOKENS[name];
}
