/**
 * Motion Effects — interaction presets pulled from the central style catalog.
 *
 * Each effect references CSS custom properties generated by Style Dictionary 5.x
 * so the source of truth remains the DTCG token files.
 */

export interface MotionEffect {
  styleId: string
  name: string
  description: string
  css: string
  /** Tailwind utility string for quick application */
  tailwind: string
}

export const MOTION_EFFECTS: Record<string, MotionEffect> = {
  'fade-in': {
    styleId: 'motion-fade-in',
    name: 'Fade In',
    description: 'Opacity entrance — 0 → 1',
    css: 'opacity: 0; transition: opacity var(--vp-motion-duration-normal) var(--vp-motion-easing-out);',
    tailwind:
      'opacity-0 transition-opacity duration-[--vp-motion-duration-normal] ease-[--vp-motion-easing-out]',
  },
  'fade-out': {
    styleId: 'motion-fade-out',
    name: 'Fade Out',
    description: 'Opacity exit — 1 → 0',
    css: 'opacity: 1; transition: opacity var(--vp-motion-duration-normal) var(--vp-motion-easing-in);',
    tailwind:
      'opacity-100 transition-opacity duration-[--vp-motion-duration-normal] ease-[--vp-motion-easing-in]',
  },
  'scale-up': {
    styleId: 'motion-scale-up',
    name: 'Scale Up',
    description: 'Entrance scale from 95% to 100%',
    css: 'transform: scale(0.95); transition: transform var(--vp-motion-duration-fast) var(--vp-motion-easing-spring);',
    tailwind:
      'scale-95 transition-transform duration-[--vp-motion-duration-fast] ease-[--vp-motion-easing-spring]',
  },
  'slide-up': {
    styleId: 'motion-slide-up',
    name: 'Slide Up',
    description: 'Translate Y entrance from 8px below',
    css: 'transform: translateY(0.5rem); transition: transform var(--vp-motion-duration-normal) var(--vp-motion-easing-out);',
    tailwind:
      'translate-y-2 transition-transform duration-[--vp-motion-duration-normal] ease-[--vp-motion-easing-out]',
  },
  'slide-down': {
    styleId: 'motion-slide-down',
    name: 'Slide Down',
    description: 'Translate Y exit to 8px below',
    css: 'transform: translateY(-0.5rem); transition: transform var(--vp-motion-duration-normal) var(--vp-motion-easing-in);',
    tailwind:
      '-translate-y-2 transition-transform duration-[--vp-motion-duration-normal] ease-[--vp-motion-easing-in]',
  },
  'pulse-glow': {
    styleId: 'motion-pulse-glow',
    name: 'Pulse Glow',
    description: 'Subtle box-shadow pulse for focus/active states',
    css: 'box-shadow: 0 0 0 0 var(--vp-color-brand-primary); transition: box-shadow var(--vp-motion-duration-slow) var(--vp-motion-easing-default);',
    tailwind:
      'shadow-[0_0_0_0_var(--vp-color-brand-primary)] transition-shadow duration-[--vp-motion-duration-slow] ease-[--vp-motion-easing-default]',
  },
}

export function getMotionEffect(key: string): MotionEffect | undefined {
  return MOTION_EFFECTS[key]
}

export function listMotionEffects(): MotionEffect[] {
  return Object.values(MOTION_EFFECTS)
}
