/**
 * Style Dictionary 5.x Configuration
 * Generates CSS custom properties and TypeScript declarations
 * from DTCG-format design tokens.
 *
 * Run: npx style-dictionary build --config sd.config.mjs
 */
import StyleDictionary from 'style-dictionary'

/**
 * Resolve the display value for a DTCG token.
 * Checks $extensions.cssValue first, then falls back to $value.
 */
function resolveValue(token) {
  if (token.$extensions?.['com.vibepulse.cssValue']) {
    return token.$extensions['com.vibepulse.cssValue']
  }
  const raw = token.$value
  if (Array.isArray(raw)) {
    return raw.join(', ')
  }
  return String(raw)
}

/**
 * Custom format: CSS custom properties with --vp- prefix
 * Produces :root { --vp-color-brand-primary: #7c3aed; ... }
 */
StyleDictionary.registerFormat({
  name: 'css/vp-custom-properties',
  format: ({ dictionary }) => {
    const lines = dictionary.allTokens.map((token) => {
      const name = token.path.join('-')
      return `  --${name}: ${resolveValue(token)};`
    })
    return `/**\n * Generated by Style Dictionary ${StyleDictionary.VERSION}\n * Do not edit directly — regenerate with: npm run tokens:build\n */\n:root {\n${lines.join('\n')}\n}\n`
  },
})

/**
 * Custom format: TypeScript declarations for all tokens
 */
StyleDictionary.registerFormat({
  name: 'typescript/vp-declarations',
  format: ({ dictionary }) => {
    const tokenEntries = dictionary.allTokens.map((token) => {
      const name = token.path.join('-')
      const cssVar = `--${name}`
      const desc = (token.$description ?? '').replace(/'/g, "\\'")
      const styleId = token.$extensions?.['com.vibepulse.styleId'] ?? name
      const val = resolveValue(token).replace(/'/g, "\\'")
      return `  '${cssVar}': { value: '${val}', description: '${desc}', styleId: '${styleId}' }`
    })

    const tokenNameUnion = dictionary.allTokens
      .map((token) => `  | '--${token.path.join('-')}'`)
      .join('\n')

    return [
      '/**',
      ` * Generated by Style Dictionary ${StyleDictionary.VERSION}`,
      ' * Do not edit directly — regenerate with: npm run tokens:build',
      ' */',
      '',
      'export type VpTokenName =',
      tokenNameUnion + ';',
      '',
      'export interface VpTokenDefinition {',
      '  value: string;',
      '  description: string;',
      '  styleId: string;',
      '}',
      '',
      'export const VP_TOKENS: Record<VpTokenName, VpTokenDefinition> = {',
      tokenEntries.join(',\n'),
      '};',
      '',
      'export function getToken(name: VpTokenName): VpTokenDefinition {',
      '  return VP_TOKENS[name];',
      '}',
      '',
    ].join('\n')
  },
})

/**
 * Custom format: Tailwind v4 preset
 */
StyleDictionary.registerFormat({
  name: 'tailwind/vp-preset',
  format: ({ dictionary }) => {
    const colorTokens = dictionary.allTokens.filter(
      (t) => t.$type === 'color',
    )
    const spacingTokens = dictionary.allTokens.filter((t) =>
      t.path.includes('spacing'),
    )
    const fontSizeTokens = dictionary.allTokens.filter(
      (t) => t.path.includes('font') && t.path.includes('size'),
    )
    const fontWeightTokens = dictionary.allTokens.filter(
      (t) => t.$type === 'fontWeight',
    )

    const colors = colorTokens
      .map((t) => `    '${t.path.slice(1).join('-')}': 'var(--${t.path.join('-')})'`)
      .join(',\n')

    const spacing = spacingTokens
      .map(
        (t) =>
          `    '${t.path[t.path.length - 1]}': 'var(--${t.path.join('-')})'`,
      )
      .join(',\n')

    const fontSize = fontSizeTokens
      .map(
        (t) =>
          `    '${t.path[t.path.length - 1]}': 'var(--${t.path.join('-')})'`,
      )
      .join(',\n')

    const fontWeight = fontWeightTokens
      .map(
        (t) =>
          `    '${t.path[t.path.length - 1]}': 'var(--${t.path.join('-')})'`,
      )
      .join(',\n')

    return [
      '/**',
      ` * Generated by Style Dictionary ${StyleDictionary.VERSION}`,
      ' * Tailwind v4 preset — maps design tokens to utility classes.',
      ' * Do not edit directly — regenerate with: npm run tokens:build',
      ' */',
      'export default {',
      '  theme: {',
      '    extend: {',
      '      colors: {',
      colors,
      '      },',
      '      spacing: {',
      spacing,
      '      },',
      '      fontSize: {',
      fontSize,
      '      },',
      '      fontWeight: {',
      fontWeight,
      '      },',
      '    },',
      '  },',
      '};',
      '',
    ].join('\n')
  },
})

export default {
  source: ['design/tokens/**/*.tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: 'design/styles/',
      files: [
        {
          destination: 'tokens.css',
          format: 'css/vp-custom-properties',
        },
      ],
    },
    ts: {
      transformGroup: 'js',
      buildPath: 'design/styles/',
      files: [
        {
          destination: 'tokens.d.ts',
          format: 'typescript/vp-declarations',
        },
      ],
    },
    tailwind: {
      transformGroup: 'js',
      buildPath: 'design/styles/',
      files: [
        {
          destination: 'tailwind-preset.js',
          format: 'tailwind/vp-preset',
        },
      ],
    },
  },
}
